services:
  postgres:
    image: postgres:16-alpine
    container_name: go-transcriber-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcriber
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: dxflrs/garage:v2.4.1
    container_name: go-transcriber-storage
    command: ["/garage", "server", "--single-node", "--default-bucket"]
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      GARAGE_DEFAULT_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      GARAGE_DEFAULT_BUCKET: ${S3_BUCKET}
    ports:
      - "3900:3900" # S3 API
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage_data:/var/lib/garage

  redis:
    image: redis:alpine3.23
    container_name: go-transcriber-redis
    restart: unless-stopped
    environment:
      - REDIS_ARGS=--appendonly yes --requirepass redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  garage_data:
  redis_data:
